### ISSUE TITLE
Unable to make on RPi3

### ISSUE THREAD

**Issue by svanimisetti** [johnbryanmoore/VL53L0X_rasp_python#1]
John, Thanks a ton for the project. I am trying to make your project on my RPi3, but am unable to progress. I am a make/linux noob. Any help will be greatly appreciated.

Info:
`pi@raspberrypi:~/VL53L0X_rasp_python $ uname -a`

> Linux raspberrypi 4.4.45-v7+ #954 SMP Fri Jan 27 19:06:40 GMT 2017 armv7l GNU/Linux

Steps:
```
cd ~
git clone https://github.com/johnbryanmoore/VL53L0X_rasp_python.git
cd VL53L0X_rasp_python/
export API_DIR=/home/pi/VL53L0X_rasp_python/Api
make
```

Symptom:

> make: *** No rule to make target 'obj/vl53l0x_api_calibration.o', needed by 'bin/vl53l0x_python'.  Stop.

**Comment by CaiB** [comment]
I'm also encountering this same error. I'm trying to download this to modify for use on a BeagleBone, but I can't get the library to compile at all (no modifications were made yet).

I will keep playing with it to see if I can figure it out (I'm not a Linux guy though). Please let me know if you find a solution to this.

**Comment by svanimisetti** [comment]
@CaiB 
I have made some progress, but only to hang up on a link error - but I am not hanging up my shoes yet. I will keep posting my finding in case it helps anyone.
Here are some suggestions to get you moving again.
The issue is that the dependencies have to modified for RPi3 (and perhaps BeagleBone) - namely, the obj files are residing in the obj folder - and the current makefile does not reflect so. Modify the Makefile on line 46 from:
`$(OBJ_DIR)/%.o:%.c`
to:
`$(LIB_OBJS):$(LIB_SRCS)`
Let me know if this solves the issue. I anticipate that the next set of errors you will find are the "multiple definition" errors. There may be ways around it too - but I am yet to find one. The search continues !!

**Comment by CaiB** [comment]
@svanimisetti Thanks for the update. Sadly, I won't have time to work on this until next weekend, so please do let me know if you find a solution.

**Comment by svanimisetti** [comment]
Finally! I have managed to get the Makefile to work. Please disregard my previous comments. There a few changes that need to be done to the Makefile. See the diff output for the changes.
```
pi@raspberrypi:~/VL53L0X_rasp_python $ diff Makefile.old Makefile
10a11
> API_DIR := $(ROOT_DIR)/Api
16c17
< 	-I${API_DIR}/Api/core/inc \
---
> 	-I$(API_DIR)/core/inc \
23c24
< 	${API_DIR}/Api/core/src \
---
> 	$(API_DIR)/core/src \

```
I am assuming that the Api folder resides in the main folder. Also, the instruction to define the env variable API_DIR was misleading. Based on actual implementation in Makefile, the main folder (VL53L0X_rasp_python) path has to be defined in $API_DIR. I have fixed that by explicitly defining that variable inside the Makefile.

I have also created a pull request #2 in case you want to review.

**Comment by johnbryanmoore** [comment]
Reviewed your pull request and it looked good. It has been committed to master.  The Makefile changes make it simpler to build and the graphing example is a nice addition.

John

**Comment by johnbryanmoore** [comment]
With regards to this running on a Beagle Bone, it should be pretty straightforward to port over. Pull the latest changes that where merged from svanimisetti that make the build process simpler first. Then check to make sure that the PYTHON_INCLUDES in the Makefile point to the correct location for the python include libraries on the Beagle Bone. You may have to install the Python Dev libraries to get it to build. On Raspberry Pi it would be:

sudo apt-get install build-essential python-dev

This should work on Beagle Bone too if running Debian.

John

**Comment by CaiB** [comment]
Awesome, we got it working. When we tried it as is, it didn't work, with GCC complaining about not finding some symbols, and suggesting we compile with -fPIC. So we edited the makefile to have -fPIC added to the parameters for both compilation operations (lines 45 & 49), did a make clean, and recompiled. Then it worked perfectly!

Thanks for your work on this API!
