### ISSUE TITLE
Solution to solve "No such file or directory" for smbus

### ISSUE THREAD

**Issue by hongbo-miao** [johnbryanmoore/VL53L0X_rasp_python#13]
To save some time for future people. 😃

At first I thought I met same issue at https://github.com/johnbryanmoore/VL53L0X_rasp_python/issues/4, but turns out the error I got is misleading.

When I tried to run the demo **VL53L0X_rasp_python/python/VL53L0X_example.py** on Raspberry 3 B+, I got the error:

> Traceback (most recent call last):
>   File "VL53L0X_example.py", line 26, in <module>
>     import VL53L0X
>   File "/home/pi/Desktop/test/VL53L0X_rasp_python/python/VL53L0X.py", line 35, in <module>
>     i2cbus = smbus.SMBus(1)
> FileNotFoundError: [Errno 2] No such file or directory

It works after enabling I2c interface with the Raspberry Pi config utility.

Here are steps:

1. Open i2c interface

    ```bash
    sudo raspi-config
    ```

2. Select Interfacing options -> I2C, choose `<Yes>` and hit Enter, then go to Finish and reboot.

**Comment by baiyijie** [comment]
Solved. Thx.

**Comment by alexey-panin** [comment]
thanks, saved me some time!

**Comment by thoschworks** [comment]
@Hongbo-Miao Thanks, saved me too (not with this project, but with a similar one...).

**Comment by mopac** [comment]
Fantastic! Saved me loads of time trying to debug my script!

**Comment by lazyoldjack** [comment]
Thanks from me too - problem solved in under 60 seconds.

**Comment by romainhk** [comment]
I love you so much. Solved in less than 30 seconds

**Comment by muratbedir** [comment]
Thanks.

**Comment by unksoldr** [comment]
Same issue I guess, but why will IC2 not enable via config at boot. To activate the readout on PoE Hat have to enable both IC2 and SPI at boot. Both are enabled at boot or should be dtparam=i2c_arm=on
                     dtparam=spi=on

**Comment by Roobyx** [comment]
Solved. Thx.

**Comment by SrConqueror** [comment]
Just wanna say thnx a lot!!!

**Comment by tdunbar12** [comment]
Thanks

**Comment by Arnaud-31** [comment]
Thanks from me - problem solved

**Comment by enjoysmath** [comment]
You saved the day!

**Comment by rafafelixphd** [comment]
Thanks. I completely overlook this issue

**Comment by Palomita2222** [comment]
TYSM! It helped me a lot for my school project!

**Comment by julian-paez27** [comment]
excelente aporte me ahorro mucho tiempo, muchas gracias

**Comment by Palomita2222** [comment]
Is there a way to open I2C with Jetson Nano?

**Comment by BeckSM64** [comment]
I've done this before and every time I forget I have to do this. Thanks for saving me some time.
