### ISSUE TITLE
Control Interface Error

### ISSUE THREAD

**Issue by ArthurXHK** [johnbryanmoore/VL53L0X_rasp_python#5]
Hi bro, I had a try on the example code `VL53L0X_example.py`. But there are some errors.

Would you know what I should do for fixing them?

Many Thanks!!

``` 
VL53L0X Start Ranging Object 0 Address 0x29

Call of VL53L0X_DataInit
API Status: -20 : Control Interface Error
Timing 20 ms
Call of VL53L0X_StopMeasurement
API Status: -20 : Control Interface Error
```

**Comment by ArthurXHK** [comment]
I tried this command `sudo i2cdetect -y 1` and found out the 0x29 was not using.

Fixed it already. Thanks for your codes!!

**Comment by sinobili** [comment]
i cant fixed this problem. Can you explain briefly? @ArthurXHK

**Comment by Bhoot123** [comment]
@sinobili @ArthurXHK 
Could either of you please explain how you fixed the problem? Mine was running fine and one day it isn't being detected anymore.

Giving the same error as in post

**Comment by Shawn2448** [comment]
I too am having this error. What was the solution?

**Comment by jayadatta** [comment]
I am also having the same issue. Any information to resolve this is highly appreciated.

**Comment by JSwaim22** [comment]
I am also having the same issue, strangely just like @Bhoot123 it was working fine one day and now it just stopped
